services:
  - type: web
    name: eatapp-web
    runtime: static
    buildCommand: npx expo export --platform web
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
